version: '3.8'

services:
  qc-systems:
    build:
      context: '.'
      dockerfile: Dockerfile
      args:
        uid: 1000
    container_name: qc-systems
    image: qc-systems
    #Not all images are available for ARM64 architecture for mac M1
    platform: linux/amd64
    ports:
      - 8000:80
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    working_dir: /var/www/html
    restart: unless-stopped
    tty: true
    volumes:
      - .:/var/www/html
    networks:
      backend:
        aliases:
          - app

  mysql-db:
    image: mysql:5.7.27
    #Not all images are available for ARM64 architecture for mac M1
    platform: linux/amd64
    container_name: mysql-db
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3307"
    environment:
      - MYSQL_ROOT_PASSWORD=root@123
      - MYSQL_DATABASE=qc_systems
      - MYSQL_USER=root
      - TZ=Asia/Tokyo
    working_dir: /var/lib/mysql
    volumes:
      - ./run/var:/var/lib/mysql
    networks:
      backend:
        aliases:
          - mysql-db

networks:
  backend:
    name: backend-network
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local